### PR TITLE
Additional options

### PR DESCRIPTION
**Pull request by Meldanen**
Hey,

Main thing is adding opacity to linestyle as it didn't work the way it was set up before (wouldn't pick up the changed opacity).

Thanks,
Alex

### CODE REVIEW

**Comment by Meldanen** [comment]
Hey,

I've also added a minInterval option to the Axis.

Thanks,
Alex

**Comment by abel533** [comment]
Thanks for your pr!
Your commit has compiled file.  such as: bin/com/github/abel533/echarts/AbstractData.class
You need to delete these files.  It is better to merge these commits into one commit.

**Comment by Meldanen** [comment]
I wasn't aware that. Sorry the mistakes, first pull request :p 
I'll let you know as soon as I resolve the compiled file issue

**Comment by abel533** [comment]
代码缩进有问题，注意查看diff。

**Comment by Meldanen** [comment]
Okay,

I'll let you know when I get the chance to fix the indentation 

Thanks,
Alex

**Comment by Meldanen** [comment]
Hi again,

If you are using Eclipse, can you share your preferences with me? It looks like I fixed most things but not everything.

Thanks,
Alex

**Comment by abel533** [comment]
我用的 IDEA，没有eclipse。这个项目需要配置 Lombok 插件。

**Comment by Meldanen** [comment]
Thank you!
I'll keep that in mind.

**Pull request merged**
